name: Version check

on: [pull_request, push]

jobs:
  check:

    strategy:
      matrix:
        java_version: [8, 11, 13]

    runs-on: ubuntu-latest

    name: Java check version ${{ matrix.java_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Build
        run: gradle shadowjar